Create and fill these accounts for max lulz
--- 
:twitter_accounts: 
- :username: johnlinns
  :password: 
:gmail_accounts: 
- :username: johnlinns
  :password: 
:myspace_accounts: 
- :email: johnlinns@gmail.com
  :password:
:yahoo_boss_api_keys:
- :api_key: 
:rapleaf_api_keys:
- :api_key:
